### ISSUE TITLE
The app does not work

### ISSUE THREAD

**Issue by Tsu-gu** [couldbejake/spotify2mp3#13]
After I enter the album link, this appears.

```
 Enter the spotify URL link: https://open.spotify.com/album/3HUbOOeUBHI0IiVllK9wHD?si=bGk371qwRlKBg0sCcYTHIw
Traceback (most recent call last):
  File "run.py", line 285, in <module>
    main()
  File "run.py", line 270, in main
    playlist_name = html.fromstring(page.content).xpath('/html/body/div/div/div/div/div[1]/div/div[2]/h1')[0].text_content().strip()
IndexError: list index out of range
```

**Comment by couldbejake** [comment]
Hi Tsu-gu, it looks like you were trying to download an album instead of a playlist.

For now you can copy all songs from the album into your own playlist and download from there.

This will be patched in a future version.

Jake
