### ISSUE TITLE
no idea what to do. on a Mac

### ISSUE THREAD

**Issue by ElijahProvis** [couldbejake/spotify2mp3#14]
here is the fail log

Good Good Things Descendents
[Errno 2] No such file or directory: '/usr/bin/ffmpeg'
Traceback (most recent call last):
  File "/Users/elijahprovis/Documents/spotify2mp3-main/run.py", line 198, in download_playlist
    clip = AudioFileClip(yt_tmp_out)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg'

**Comment by couldbejake** [comment]
Hi Elijah, it looks like you were trying to download an album instead of a playlist.

For now you can copy all songs from the album into your own playlist and download from there.

This will be patched in a future version.

Jake

**Comment by couldbejake** [comment]
Does running the command;

`pip3 install --user ffmpeg-python`

Fix the issue?

**Comment by couldbejake** [comment]
I need a little more information to help you, if you still need help!
