### ISSUE TITLE
list index

### ISSUE THREAD

**Issue by shortaktien** [couldbejake/spotify2mp3#15]
```
list index out of range
Traceback (most recent call last):
  File "/Users/xxx/spotify2mp3/run.py", line 158, in download_playlist
    yt_data = json.loads(ya_results)['videos'][0]
IndexError: list index out of range

```
after 30 songs was aborted, with this code

**Comment by couldbejake** [comment]
can you send the playlist you were trying to download and update the requirement pytube?

**Comment by secondary-smiles** [comment]
I encountered the same issue, here was my `failed_log.txt`
```
list index out of range
Traceback (most recent call last):
  File "/Users/***/Desktop/spotify2mp3/run.py", line 158, in download_playlist
    yt_data = json.loads(yt_results)['videos'][0]
IndexError: list index out of range
```

I haven't looked at `run.py` enough, but it looks like it's not checking to make sure that the array is empty before trying to access it.
