### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by DurgeshKavate003** [couldbejake/spotify2mp3#26]
when i put the url `https://open.spotify.com/playlist/649OfpVgIVrppB0zRV7kAJ` it showed the error list index out of range. and when i tried only putting the spotify playlist id `649OfpVgIVrppB0zRV7kAJ` there was the same list index out of range error..

full error as follows :-
`
Enter the spotify URL link: https://open.spotify.com/playlist/649OfpVgIVrppB0zRV7kAJ
Traceback (most recent call last):
  File "d:\Durgesh Files\Programming\spotify2mp3\spotify2mp3\run.py", line 296, in <module>
    main()
  File "d:\Durgesh Files\Programming\spotify2mp3\spotify2mp3\run.py", line 281, in main
    playlist_name = html.fromstring(page.content).xpath('/html/body/div/div/div/div/div[1]/div/div[2]/h1')[0].text_content().strip()
IndexError: list index out of range`

and when i tried putting only the id :- 

`Enter the spotify URL link: 649OfpVgIVrppB0zRV7kAJ
Traceback (most recent call last):
  File "d:\Durgesh Files\Programming\spotify2mp3\spotify2mp3\run.py", line 296, in <module>
    main()
  File "d:\Durgesh Files\Programming\spotify2mp3\spotify2mp3\run.py", line 281, in main
    playlist_name = html.fromstring(page.content).xpath('/html/body/div/div/div/div/div[1]/div/div[2]/h1')[0].text_content().strip()
IndexError: list index out of range`

**Comment by couldbejake** [comment]
@DurgeshKavate003 You should now be asked to enter text, if a playlist name couldn't be found.

Please let me know if this solves your issue.

Thanks!

**Comment by DurgeshKavate003** [comment]
Thanks a lot... I will try and let you know as soon as possible...
