### ISSUE TITLE
Error while installing requirements

### ISSUE THREAD

**Issue by Akitakek** [couldbejake/spotify2mp3#39]
Python version: 3.12
Elevated powershell: `pip3 install -r requirements.txt`

```
Collecting beautifulsoup4==4.11.1 (from -r requirements.txt (line 1))
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting bs4==0.0.1 (from -r requirements.txt (line 2))
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting certifi==2021.10.8 (from -r requirements.txt (line 3))
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.12 (from -r requirements.txt (line 4))
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting coverage==5.5 (from -r requirements.txt (line 5))
  Using cached coverage-5.5.tar.gz (691 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting decorator==4.4.2 (from -r requirements.txt (line 6))
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting deprecation==2.1.0 (from -r requirements.txt (line 7))
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting eyed3==0.9.6 (from -r requirements.txt (line 8))
  Using cached eyeD3-0.9.6-py3-none-any.whl (245 kB)
Collecting filetype==1.0.13 (from -r requirements.txt (line 9))
  Using cached filetype-1.0.13-py2.py3-none-any.whl (17 kB)
Collecting idna==3.3 (from -r requirements.txt (line 10))
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imageio==2.19.2 (from -r requirements.txt (line 11))
  Using cached imageio-2.19.2-py3-none-any.whl (3.4 MB)
Collecting imageio-ffmpeg==0.4.7 (from -r requirements.txt (line 12))
  Using cached imageio_ffmpeg-0.4.7-py3-none-win_amd64.whl (22.6 MB)
Collecting moviepy==1.0.3 (from -r requirements.txt (line 13))
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.22.3 (from -r requirements.txt (line 14))
  Using cached numpy-1.22.3.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\akitake\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\akitake\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\akitake\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\akitake\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\akitake\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1216, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1237, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 841, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "C:\Users\akitake\AppData\Local\Temp\pip-build-env-nkpz_tt3\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\akitake\AppData\Local\Temp\pip-build-env-nkpz_tt3\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\akitake\AppData\Local\Temp\pip-build-env-nkpz_tt3\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by couldbejake** [comment]
Can you try using Python 3.8?

**Comment by couldbejake** [comment]
Python 3.12 is not officially supported
