### ISSUE TITLE
Error when downloading a playlist

### ISSUE THREAD

**Issue by gbrlsfernandez** [couldbejake/spotify2mp3#40]
Hi, good day! I'm receiving this error when I tried to download a playlist from Spotify. 
Tried searching for any fix to this but couldn't. Tried 2 more playlists with the same error.

```

Searching for song: The Most Beautiful Thing by Bruno Major
   - Downloading the song, please wait
Traceback (most recent call last):
  File "spotify2mp3.py", line 164, in <module>
    main(playlist=url, quality=quality, min_views=DEFAULT_MIN_VIEWS_FOR_DOWNLOAD, max_length=DEFAULT_MAX_LENGTH_FOR_DOWNLOAD)
  File "spotify2mp3.py", line 110, in main
    success =downloader.download_playlist(playlist)
  File "C:\Users\gbrls\Documents\Spotify Downloader\spotify2mp3\downloader.py", line 91, in download_playlist
    self.download_track(None, track, "downloads/playlists/" + playlist.get_title(True) + "/", True)
  File "C:\Users\gbrls\Documents\Spotify Downloader\spotify2mp3\downloader.py", line 150, in download_track
    video_downloaded_path, self.audio_quality = self.youtube_client.download(youtube_link, self.audio_quality)
  File "C:\Users\gbrls\Documents\Spotify Downloader\spotify2mp3\apis\youtube.py", line 41, in download
    youtube_video_streams = youtube_video.streams.filter(only_audio=True)
  File "C:\Users\gbrls\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\gbrls\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\gbrls\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\gbrls\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 264, in bypass_age_gate
    raise exceptions.AgeRestrictedError(self.video_id)
pytube.exceptions.AgeRestrictedError: 1nml-_YE2OU is age restricted, and can't be accessed without logging in.


```

Python version: 3.8.10 (Was having installation issues with 3.11, so I downgraded to 3.8)
Possible Issue: pytube.exceptions.AgeRestrictedError: 1nml-_YE2OU is age restricted, and can't be accessed without logging in.

Affected Songs in 3 Different Playlists: 

- The Most Beautiful Thing by Bruno Major
- Dance The Night - From Barbie The Album by Dua Lipa
- Put My Hands On You by DEAN Anderson .Paak

Thanks for the awesome work!

**Comment by couldbejake** [comment]
Pull request #36 should fix your issue. Sorry for the late reply.

We have updated the application, so you must be logged in.

However:
- A new pytube issue - a result from an update to YouTube has arisen and prevents downloads, adding a patch now.
- Being logged in allows us to download your personal playlists such as liked songs.
