### ISSUE TITLE
Git bash issue

### ISSUE THREAD

**Issue by Zied-Sifaoui** [couldbejake/spotify2mp3#49]
```
(Name of my computer) MINGW64 ~/spotify2mp3 (main)
$ python spotify2mp3.py
Traceback (most recent call last):
  File "C:\Users\Assayes2.0\spotify2mp3\spotify2mp3.py", line 202, in <module>
    utils.print_splash_screen()
  File "C:\Users\Assayes2.0\spotify2mp3\utils.py", line 18, in print_splash_screen
    print(colours.SPOTIFYGREEN + '''
  File "C:\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 51-65: character maps to <undefined>
```

my python is updated

**Comment by couldbejake** [comment]
Hi Zied, can you try using Python 3.8 instead? Python 3.12 is not supported.
