### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jeviix** [couldbejake/spotify2mp3#51]
ali@DESKTOP-MOIQDK7 MINGW64 ~/spotify2mp3 (main)
$ python spotify2mp3.py
Traceback (most recent call last):
  File "spotify2mp3.py", line 202, in <module>
    utils.print_splash_screen()
  File "C:\Users\ali\spotify2mp3\utils.py", line 18, in print_splash_screen
    print(colours.SPOTIFYGREEN + '''
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 51-65: character maps to <undefined>

ali@DESKTOP-MOIQDK7 MINGW64 ~/spotify2mp3 (main)
$ python --version
Python 3.8.10

**Comment by otmanzy99** [comment]
Have the same error.
