### ISSUE TITLE
KeyError: 'streamingdata'

### ISSUE THREAD

**Issue by 0xAdachi** [couldbejake/spotify2mp3#63]
- Downloading, please wait
Traceback (most recent call last):
  File "spotify2mp3.py", line 206, in <module>
    main(authtype=authtype, song=url, quality=quality, min_views=DEFAULT_MIN_VIEWS_FOR_DOWNLOAD, max_length=DEFAULT_MAX_LENGTH_FOR_DOWNLOAD)
  File "spotify2mp3.py", line 164, in main
    success = downloader.download_track(song)
  File "/home/adachi/spotify2mp3/downloader.py", line 189, in download_track
    video_downloaded_path, self.audio_quality = self.youtube_client.download(youtube_link, self.audio_quality)
  File "/home/adachi/spotify2mp3/apis/youtube.py", line 57, in download
    youtube_video_streams = youtube_video.streams.filter(only_audio=True)
  File "/home/adachi/.local/lib/python3.8/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/adachi/.local/lib/python3.8/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/adachi/.local/lib/python3.8/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

**Comment by 0xAdachi** [comment]
how to fix ?
