### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saiftheboss7** [couldbejake/spotify2mp3#9]
After yesterday's fixes, I tried today again but facing this issue after running the script

`View Count: 1,70,10,808টি ভিউ
Duration: 3:42

Traceback (most recent call last):
  File "/Users/saif/Downloads/spotify2mp3/run.py", line 276, in <module>
    main()
  File "/Users/saif/Downloads/spotify2mp3/run.py", line 270, in main
    download_playlist(spotify_url_link, playlist_name)
  File "/Users/saif/Downloads/spotify2mp3/run.py", line 182, in download_playlist
    yt_vid_obj = yt_dl_obj.streams.filter(only_audio=True).first()
  File "/opt/homebrew/lib/python3.9/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/opt/homebrew/lib/python3.9/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/opt/homebrew/lib/python3.9/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/opt/homebrew/lib/python3.9/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests`

**Comment by couldbejake** [comment]
It looks like you tried to download too many songs in a short space of time.

Are you able to download songs now that some time has elapsed?

**Comment by saiftheboss7** [comment]
Hi @couldbejake - I tried again today after your comment and faced this new issue

<img width="639" alt="CleanShot 2022-06-02 at 16 56 35@2x" src="https://user-images.githubusercontent.com/19363738/171614915-16b228d7-e633-40c1-aeb1-d5274f128ed0.png">


Including the log file here
[failed_log.txt](https://github.com/couldbejake/spotify2mp3/files/8823122/failed_log.txt)

**Comment by couldbejake** [comment]
It looks like pytube has been slightly broken by a API change from YouTube.

There's a temporary patch available, to install do the following:

`pip3 uninstall pytube`

`python3 -m pip install git+https://github.com/JazPin/pytube`

If you have any other questions feel free to open another ticket.

**Comment by saiftheboss7** [comment]
Just wanted to mention it's fixed now. @couldbejake Thanks for the awesome script! 🙌 🎉

**Comment by couldbejake** [comment]
> Just wanted to mention it's fixed now. @couldbejake Thanks for the awesome script! 🙌 🎉

Good to hear, thank you very much!
